### ISSUE TITLE
No Action and Gesture

### ISSUE THREAD

**Issue by 2ynhub** [junkfactory/chrome-simple-gestures#10]
<img width="397" alt="g35" src="https://github.com/junkfactory/chrome-simple-gestures/assets/55008500/7bb92f54-a690-4765-83a0-d07244f73249">

I am using this extension on 126.0.6478.126(Official Build, ungoogled-chromium) (arm64). And, I can't see Actions and Gestures at the setting. Even though I can't see them, Actions and Gestures are working I think.

I don't understand why they are not appeared. Is there anything I can check?

Thanks in advance

**Comment by junkfactory** [comment]
Try enabling developer mode in the extensions page and inspect "service worker". See if the console is logging some errors.

![image](https://github.com/junkfactory/chrome-simple-gestures/assets/2998269/c4f5e610-1952-40c1-8d0b-d4d9d2281e28)

Seems to be working for me though
![image](https://github.com/junkfactory/chrome-simple-gestures/assets/2998269/2c6a2464-107c-4f3e-978c-3c04ac783785)

**Comment by 2ynhub** [comment]
@junkfactory

Thanks for your reply. :)

First of all, 'service worker' was not active or enabled before I click it.

After I clicked 'Save configuration', I got 27 warnings.

<img width="692" alt="1" src="https://github.com/junkfactory/chrome-simple-gestures/assets/55008500/c94e4a19-59c6-435b-82cd-c51ddf50dedc">


<img width="983" alt="2" src="https://github.com/junkfactory/chrome-simple-gestures/assets/55008500/0f9ffb04-cfae-43ba-83a1-79baca249fc9">

And, there is red error tab at the chrome://extensions/ page.

<img width="411" alt="3" src="https://github.com/junkfactory/chrome-simple-gestures/assets/55008500/bb75a2f2-df68-4f37-ac61-a1bbecf2805a">

That is like below image.

<img width="666" alt="4" src="https://github.com/junkfactory/chrome-simple-gestures/assets/55008500/fb244124-eac7-4dfd-8caf-5c91e06bb7a6">

The meaning of words inside () is anonymous function.

Is there anything I can let you know?

**Comment by junkfactory** [comment]
I think i know what's going on there. If you're willing to try. Download the file below. Rename the file from `chrome-simple-gestures.zip` to `chrome-simple-gestures.crx`. Then drag and drop into "My Extensions" page.

[chrome-simple-gestures.zip](https://github.com/user-attachments/files/16117992/chrome-simple-gestures.zip)

If it works for you i'll update in the webstore

**Comment by 2ynhub** [comment]
@junkfactory

It's working.

<img width="405" alt="5" src="https://github.com/junkfactory/chrome-simple-gestures/assets/55008500/4d763aa0-c031-4bf9-b23a-952b4d1533bf">

Thank you. :)
