### ISSUE TITLE
No Trail when dragging from an image

### ISSUE THREAD

**Issue by Bush-cat** [junkfactory/chrome-simple-gestures#13]
When you start to drag form an Image or video, maybe other types of contents too, no trail will appear.

You can try it on youtube videos, or any Image

**Comment by Bush-cat** [comment]
*it works on some images, like on github and on expanded images on duckduckgo, but the normal search result images or youtube thumbnails still cause the problem

I also looked into the console of the service worker but it didn't print anything

The Action still works, just no trail appears

**Comment by junkfactory** [comment]
@Bush-cat if you're cool with testing the zip file attached on the #14 . Would love to hear how it goes for you. Thx

**Comment by Bush-cat** [comment]
Before testing your fix, I noticed errors in the webstore version on several sites
Error: Canvas not found
Stack Trace:
src/canvas.js:48 (destroyCanvas)
src/simple_gestures.js:123 (document.onmouseup)

Your Patch completely fixed the problem on duckduckgo images, no errors there but the errors still appear on other sites
There was the same error on this github issue site but I didn't notice anything and there were no images.

On Youtube it is half fixed, it appears only in the Area at the top of the page in the window, when you scroll down and start a drag from there, you see no trail until you get to the area you saw at the top of the page, same Errors and Stacktrace as above.
![image](https://github.com/user-attachments/assets/f912adb8-6a4a-4ed7-8a6c-29cda50370ba)

For additional Context, I run Brave 1.68.137 Chromium: 127.0.6533.100 (Official Build) (64-bit) on Windows 11

**Comment by Bush-cat** [comment]
I tried Youtube with the webstore version again, it has the same behaviour but much earlier in the window, you get it right at the beginning of the page, fixed area no matter how big the window is and the webstore version didn't throw any errors about it.

![image](https://github.com/user-attachments/assets/70e81335-df5a-464c-9b25-49274a5b173e)

**Comment by junkfactory** [comment]
Got it.  Try this one, I think this should handle those. `Canvas not found` is for troubleshooting won't affect functionality.

[chrome-simple-gestures-snapshot3.zip](https://github.com/user-attachments/files/16606372/chrome-simple-gestures-snapshot3.zip)

**Comment by Bush-cat** [comment]
Nice, the snapshot fixed the Issue, you can still experience it when you scroll while dragging but that's not a dealbreaker for me

**Comment by junkfactory** [comment]
Thanks for assisting Bush-cat
